google=https://www.google.com/

# Naukri login configuration
naukri.login.url=https://www.naukri.com/
naukri.user=shivamparashar1213@gmail.com
naukri.password=shivam1213

# Testing URL
naukri.test=https://www.naukri.com/job-listings-ai-automation-engineer-makcliff-mysuru-2-to-6-years-240326035968?src=sortby&sid=17743614023367003_3&xp=1&px=1&nignbevent_src=jobsearchDeskGNB
naukri.female=https://www.naukri.com/job-listings-access-healthcare-immediate-hiring-ipdrg-coders-qa-access-healthcare-noida-hyderabad-thiruvananthapuram-3-to-8-years-260326024791?src=sortby&sid=17745815780631676_8&xp=19&px=6&nignbevent_src=jobsearchDeskGNB
nokri.testCh=https://www.naukri.com/job-listings-security-consultant-infoshare-soft-mumbai-all-areas-2-to-6-years-160126015135?src=sortby&sid=17746125175376950_3&xp=10&px=1&nignbevent_src=jobsearchDeskGNB

notice.joblink=https://www.naukri.com/job-listings-mega-wlakin-for-design-control-or-change-control-or-dhf-on-18th-apr-hcltech-chennai-1-to-6-years-160426031566?src=sortby&sid=17763418630454621_3&xp=6&px=1&nignbevent_src=jobsearchDeskGNB